[tool.poetry]
name = "mad-prefect"
version = "0.1.0"
description = ""
authors = ["Maitland Marshall <maitland@mait.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
prefect = "^2.13.4"
pandas = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
